export const lastFmActions = {
  FETCH_LAST_FM: "FETCH_LAST_FM",
  FETCH_LAST_FM_SUCCESS: "FETCH_LAST_FM_SUCCESS",
  FETCH_LAST_FM_ERRORS: "FETCH_LAST_FM_ERRORS",
  FETCH_LAST_FM_WEEKS: "FETCH_LAST_FM_WEEKS",
  FETCH_LAST_FM_WEEKS_SUCCESS: "FETCH_LAST_FM_WEEKS_SUCCESS",
  FETCH_LAST_FM_WEEKS_ERRORS: "FETCH_LAST_FM_WEEKS_ERRORS",
  RESET_LAST_FM: "RESET_LAST_FM"
}

export const userActions = {
  FETCH_USER_DATA: "FETCH_USER_DATA",
  FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
  FETCH_USER_DATA_ERRORS: "FETCH_USER_DATA_ERRORS"
}

export const albumInfosActions = {
  FETCH_ALBUMS_INFOS: "FETCH_ALBUMS_INFOS",
  FETCH_ALBUMS_INFOS_SUCCESS: "FETCH_ALBUMS_INFOS_SUCCESS",
  FETCH_ALBUMS_INFOS_ERRORS: "FETCH_ALBUMS_INFOS_ERRORS"
}