export const lastFmActions = {
  FETCH_LAST_FM: "FETCH_LAST_FM",
  FETCH_LAST_FM_SUCCESS: "FETCH_LAST_FM_SUCCESS",
  FETCH_LAST_FM_ERRORS: "FETCH_LAST_FM_ERRORS"
}

export const userActions = {
  FETCH_USER_DATA: "FETCH_USER_DATA",
  FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
  FETCH_USER_DATA_ERRORS: "FETCH_USER_DATA_ERRORS"
}